#version: '3.8'

services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hotel-management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:  ["CMD","mysqladmin","ping","-h","localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - hotel_network


  hotel-management-app:
#    image: gayan0226/hotel:test1
    build: .
    container_name: hotel-management-app
    volumes:
      - ./log_data:/logs
    restart: on-failure
    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/hotel-management?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      SPRING_APPLICATION_NAME: hotel-management
      SERVER_PORT: 8081
      DB_HOST: host.docker.internal
      DB_PORT: 3306
    ports:
      - "8083:8081"
    depends_on:
       mysql:
         condition: service_healthy
    networks:
      - hotel_network

volumes:
  mysql_data:
  log_data:
networks:
  hotel_network:
    driver: bridge